### ISSUE TITLE
Parser: error in setting of the date of "today" tasks

### ISSUE THREAD

**Issue by nehhhhmiah** [cs2103jan2015-w11-3c/main#91]
if you enter "add do this today", it correctly reads the task as "do this" and sets the task type as deadline and sets the time to 2359. But i think you're setting the date 1less that it should be, so if i added the task today (10/04), it's set as (10/03).

@yeohjo

**Comment by yeohjo** [comment]
On my separate project, it runs fine and returns the correct date.
Lemme push up my code
